name = "mcpheonix-worker"
main = "durable-objects-worker.js"
compatibility_date = "2023-09-01"

[durable_objects]
bindings = [
  { name = "MCPHEONIX_OBJECT", class_name = "MCPheonixObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["MCPheonixObject"] 